# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5b2ca490f1ac9a0ec17a1e07fd2548219b93b584317750f9d01c1fcba26b2e836dded24233b2ea0411f4122f61255a849b517b78bcfee7b292f1ce478985301

test:
  secret_key_base: fda1bf63221a9122538ad94f6c702c1e3fa35c7c762d3c4ff8e167265a431206e5c68de8a97883d6dbad96a4f24a64b1701c10dbce21810911961c91224798b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
